#!/bin/bash

## #ddev-generated
## Description: Install the lullabot/ddev-playwright addon and does some basic onex config.
## Usage: 1x-playwright-install

start=`date +%s`

# Colors for printing messages.
RED='\033[0;31m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Installing playwright (within DDEV):${NC}"
ddev get lullabot/ddev-playwright
ddev restart

ddev exec -d /var/www/html/ mkdir -p test/playwright
# Adjust for 1X-internet private repository
echo -e "${GREEN}Adjust .npmrc${NC}"
pushd $DDEV_APPROOT/test/playwright && echo '@dxp:registry=https://git.1xinternet.de/api/v4/packages/npm/' >> .npmrc ; popd

# To install with npx.
pushd $DDEV_APPROOT/test/playwright && npx --yes @1xinternet/create-dxp-playwright --lang=Javascript --quiet

if [! ddev exec "command -v jq" &> /dev/null ]; then
    echo -e "${RED}jq command not found in ddev web container - you'll need to adjust the test/playwright/playwright.config.ts manually!"
else
    ddev_hostname=`ddev status -j | ddev exec jq -r .raw.hostnames[0]`
    # @todo: better templating of this, e.g. we normally *don't* test in parallel in 4 browsers ...
    # Make this work on MacOS and Linux >.<
    if [[ $OSTYPE == darwin* ]]; then
      pushd $DDEV_APPROOT/test/playwright && sed -i '' "s@http://127.0.0.1:3000@https://${ddev_hostname}@g" playwright.config.ts && popd
    else
      pushd $DDEV_APPROOT/test/playwright && sed -i "s@http://127.0.0.1:3000@https://${ddev_hostname}@g" playwright.config.ts && popd
    fi

fi

# Install playwright *inside* the ddev container (see lullabot/ddev-playwright)
ddev install-playwright