#!/bin/bash

## #ddev-generated
## Description: Installs playwright on the host computer (NOT INSIDE DDEV!)
## Usage: 1x-playwright-host-install

start=`date +%s`

# Colors for printing messages.
RED='\033[0;31m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Installing playwright (on HOST):${NC}"

if ! command -v npx 2>&1 >/dev/null
then
    echo -e "${RED}'npx'-command not found on the host machine - you'll need to install nodejs before - if you have questions, please contact #devops or #developer-channel."
    exit 0;
fi

echo -e "Please note this will install playwright on your HOST machine - *not* inside DDEV!\n"

echo -e "Creating test-directory $DDEV_APPROOT/test/playwright"
mkdir -p $DDEV_APPROOT/test/playwright

# Adjust for 1X-internet private repository
# @todo probably this should be removed.
echo -e "${GREEN}Adjust .npmrc${NC}"
pushd $DDEV_APPROOT/test/playwright && echo '@dxp:registry=https://git.1xinternet.de/api/v4/packages/npm/' >> .npmrc ; popd

# To install with npx.
pushd $DDEV_APPROOT/test/playwright && npx --yes @1xinternet/create-dxp-playwight --lang=Javascript --quiet

echo -e "\n${CYAN}Please check above for any comments/errors: you might have to run 'npx  to test/playwright\n\n"
echo -e "${GREEN}To run tests change to 'test/playwright/' directory ('cd $DDEV_APPROOT/test/playwright/') and run 'npx playwright test example'\n"
