#!/usr/bin/env bash

## #ddev-generated
## Description: Install the lullabot/ddev-playwright addon and does some basic onex config.
## Usage: 1x-playwright-install

start=`date +%s`

# Colors for printing messages.
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Make sure the container is alive.
ddev start

# Let's make sure @dxp-scoped package registry is defined as it required in the starterkit below.
DXP_REGISTRY=$(ddev exec "npm config get @dxp:registry")

if [ -z "$DXP_REGISTRY" ] ; then
    echo "The @dxp-scope is not configured inside the container aborting. Consider running the command 'ddev 1x-token-setup'!"
    exit 1
fi

echo -e "${GREEN}Installing playwright (within DDEV):${NC}"
ddev add-on get lullabot/ddev-playwright
ddev restart

[ "${DDEV_MUTAGEN_ENABLED:-}" = "true" ] && ddev mutagen sync
# Make sure we have a test/playwright-folder.
ddev exec -d /var/www/html/ "mkdir -p test/playwright"
# Empty JSON so the `ddev install-playwright` actually installs.
[ "${DDEV_MUTAGEN_ENABLED:-}" = "true" ] && ddev mutagen sync
ddev exec -d /var/www/html/test/playwright 'echo "{}" > ./package.json'

[ "${DDEV_MUTAGEN_ENABLED:-}" = "true" ] && ddev mutagen sync
# Install playwright *inside* the ddev container (see lullabot/ddev-playwright)
ddev install-playwright

[ "${DDEV_MUTAGEN_ENABLED:-}" = "true" ] && ddev mutagen sync
# Use our forked starterkit https://github.com/1xINTERNET/create-dxp-playwright to scaffold.
ddev exec -d /var/www/html/test/playwright "npx --yes 1xINTERNET/create-dxp-playwright --lang=Javascript --quiet"
