#!/bin/bash

## #ddev-generated
## Description: Install the lullabot/ddev-playwright addon and does some basic onex config.
## Usage: 1x-playwright-install

start=`date +%s`

# Colors for printing messages.
RED='\033[0;31m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Installing playwright (within DDEV):${NC}"
ddev add-on get lullabot/ddev-playwright
ddev restart

ddev exec -d /var/www/html/ "mkdir -p test/playwright"

# Let's make sure all the @dxp-scoped package is defined.
DXP_REGISTRY=$(ddev exec "npm config get @dxp:registry")

if [ -z "$DXP_REGISTRY" ] ; then
    echo "The @dxp-scope is not configured inside the container aborting. Consider running the command 'ddev 1x-token-setup'!"
    exit 1
fi

# Use our forked starterkit https://github.com/1xINTERNET/create-dxp-playwright to scaffold.
ddev exec -d /var/www/html/test/playwright "npx --yes @1xinternet/create-dxp-playwright --lang=Javascript --quiet"

# Install playwright *inside* the ddev container (see lullabot/ddev-playwright)
ddev install-playwright