#!/bin/bash
## #ddev-generated
## Description: Run phpcs within the web container
## Usage: 1x-phpcs
## Example: "ddev 1x-phpcs --basepath=. --colors ./web/modules/contrib/crop/"

# Note: we already start in the base dir.
./vendor/bin/phpcs "$@"